### ISSUE TITLE
TWRP installation fails if recovery doesn't have awk

### ISSUE THREAD

**Issue by hamedsbt** [FriendlyNeighborhoodShane/MinMicroG#1]
TWRP installation failed:
**awk is not available**

How to fix it?

**Comment by FriendlyNeighborhoodShane** [comment]
Hello!

The installation script needs the awk tool for processing data. But for some reason rare recoveries don't include it (This is actually the 4th time I've seen this error).

I fixed this problem by piggybacking on Magisk's busybox a while after the last release. So if you use Magisk, then I can make you a new release that will work after you flash Magisk (you can still force it to install to system though).

If you do not use Magisk, then sorry, I can't do much. You can ask your recovery dev to include awk, or you can use a different recovery.

Long-term, I'm just thinking I'll rewrite the script to remove the awk dependency. Rare as it may be, it's quite annoying.

**Comment by FriendlyNeighborhoodShane** [comment]
Sooo I made a release (A couple hours ago) that should work if you have Magisk installed.

I'm afraid that's all I can do for now, until I write out the awk dependency.

**Comment by FriendlyNeighborhoodShane** [comment]
Fixed with f3a1729558d7da5017e93a45568a95a7a30366fe

Feel free to selfbuild now, but I don't think I'll be making a release until there are updates.
