### ISSUE TITLE
MinMicrog and Shelter

### ISSUE THREAD

**Issue by letkan** [FriendlyNeighborhoodShane/MinMicroG#11]
When using [Shelter](https://github.com/PeterCxy/Shelter) Playstore (PatchPhonesky) app's signature is nor recognized in the work profile though it is in the regular one. I built a zip with the real Phonesky and the signature was recognized in both. I don't know if this is a MinMicrog (PatchPhonesky) issue or a Shelter one. This is on Android 10 (crDroid) BTW.

Never mind, I solved this with `pm grant --user 10 com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE`

**Comment by FriendlyNeighborhoodShane** [comment]
Oh, cool. You could also have ran `npem`, that takes care of almost every permission problem.
