### ISSUE TITLE
Why not AuroraStore?

### ISSUE THREAD

**Issue by rugk** [FriendlyNeighborhoodShane/MinMicroG#12]
Why do you use FakeStore and not the new Aurora Store?

**Comment by FriendlyNeighborhoodShane** [comment]
Where not AuroraStore?

All non-minimal non-Playstore packages have Aurora Store along with Fakestore.

**Comment by rugk** [comment]
Ah ok fine. The Readme just talks of FakeStore, that's why I wondered…
