### ISSUE TITLE
Questions regarding MinimalIAP

### ISSUE THREAD

**Issue by MeltEnvy** [FriendlyNeighborhoodShane/MinMicroG#15]
I've been using the NoGoolag edition for a while now and it has been wonderful, never ran into permission issues or any other trouble, which often happened with other MicroG packages and I appreciate what you do.

As I wanted to start using in app purchases I tried switching to MinimalIAP, but can't seem to make it work. After signing in to the Playstore, it does not load but simply displays the logo, in addition to this (or perhaps the cause of),  the self-check shows that Phonesky does not have the correct signature. I'm not sure if this is intended due to the modified store, or if there's an issue with my installation.

**Comment by FriendlyNeighborhoodShane** [comment]
Hello! Glad you found this useful :)

Yep, the signature box is supposed to be checked. You can just run `npem` from a root terminal or ADB to grant all permissions to it.

If that still doesn't make it work, there's a part in the troubleshooting guide: https://github.com/FriendlyNeighborhoodShane/MinMicroG/blob/master/install.md#play-store-rh-01-error

**Comment by MeltEnvy** [comment]
Manually granting Playstore signature spoofing worked, it is now crossed in MicroG along with all other permissions. It unfortunately did not solve accessing playstore, as it is still does nothing but load the logo. Worth nothing I also tried the standard package, which had the same result. Both were flashed via TWRP, not Magisk.
