### ISSUE TITLE
New maintenance releases of MicroG

### ISSUE THREAD

**Issue by duartec3000** [FriendlyNeighborhoodShane/MinMicroG#20]
First of all thank you so much for this awesome project it is by far the best experience in installing MicroG and related technologies.

There have been 3 maintenance releases of MicroG since the last release of MinMicroG Installer: https://github.com/microg/GmsCore/releases

Would it be possible to include these in the MinMicroG Installer? 

Thank you!

**Comment by rishabharidas** [comment]
Click this release  [https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI](MinMicroG-abuse-CI ) it has all updated ones

**Comment by FriendlyNeighborhoodShane** [comment]
It's always possible to update everything from the official F-Droid repositories, so I don't make releases on every small update. I will be making a release on the next microG update, as it is likely to contain important fixes.

As has been mentioned above, there is a CI repo that makes automated builds whenever something has been updated, if you really do need them. Make sure to read the warnings in the readme there before using them!
