### ISSUE TITLE
Needs TWRP 

### ISSUE THREAD

**Issue by y0va** [FriendlyNeighborhoodShane/MinMicroG#21]
Yesterday I flashed the UNLP on a fresh lineageOS 18.1 on a LG G3 d855.  

I usually just use the lineage recovery, so I noticed that the update-binary from this package needs TWRP. With lineageos recovery it fails on line 105 when checking for available shell commands.  

This could maybe solved by providing an own busybox, but for the ease one could just mention this requirement in the Readme.

**Comment by FriendlyNeighborhoodShane** [comment]
Yeah, the LOS recovery toybox usually doesn't come compiled with several of those bells and whistles needed. This should probably be mentioned in the instructions.

Bundling a busybox is an option but one I'm not really considering ATM because I want this to be easily self-buildable by everybody.

**Comment by FriendlyNeighborhoodShane** [comment]
Added note in 4beff5812163bab440174daf94d73c4ce22d12fe.
