### ISSUE TITLE
Google Sync adapters

### ISSUE THREAD

**Issue by kielichwina** [FriendlyNeighborhoodShane/MinMicroG#24]
Google Sync adapters for android 11 (Arrow OS) not working. No callendar, no contacts.

**Comment by FriendlyNeighborhoodShane** [comment]
Go to a root terminal or adb shell and run:
```
npem
```

What does it say?

Have you logged in and turned on device registration in microg settings? Make sure sync in turned on in Android Settings > Accounts > [your google account.]

**Comment by kielichwina** [comment]
~ $ su
:/data/data/com.termux/files/home # npem
package com.google.android.gms found
already has permission android.permission.FAKE_PACKAGE_SIGNATURE
package com.android.vending found
already has permission android.permission.FAKE_PACKAGE_SIGNATURE
package com.google.android.gms found
already has permission android.permission.ACCESS_COARSE_LOCATION
package org.microg.nlp.backend.ichnaea found
already has permission android.permission.ACCESS_COARSE_LOCATION
package org.fitchfamily.android.dejavu found
already has permission android.permission.ACCESS_COARSE_LOCATION
package org.microg.nlp.backend.apple found
already has permission android.permission.ACCESS_COARSE_LOCATION
package com.google.android.gms found
already has permission android.permission.ACCESS_FINE_LOCATION
package org.microg.nlp.backend.ichnaea found
already has permission android.permission.ACCESS_FINE_LOCATION
package org.fitchfamily.android.dejavu found
already has permission android.permission.ACCESS_FINE_LOCATION
package org.microg.nlp.backend.apple found
already has permission android.permission.ACCESS_FINE_LOCATION
package com.google.android.gms found
already has permission android.permission.ACCESS_BACKGROUND_LOCATION
package com.google.android.gms found
already has permission android.permission.RECEIVE_SMS
:/data/data/com.termux/files/home #

![Screenshot_20220119-105514_Ustawienia_1](https://user-images.githubusercontent.com/72478292/150115653-8e1373f2-44c5-4616-8eb6-8b193e88df22.png)

![Screenshot_20220119-105604_Ustawienia_1](https://user-images.githubusercontent.com/72478292/150115693-c46eb38b-f28d-4e04-aff1-caab81062680.png)

There's no calendar or contacts inside sync window

**Comment by kielichwina** [comment]
Sync is turned on
![Screenshot_20220119-115108_Ustawienia_1](https://user-images.githubusercontent.com/72478292/150116032-652677bd-88bb-43ce-b119-859b1d049429.png)

MicroG all selfchecks enabled.

![Screenshot_20220119-115428_Usługi microG](https://user-images.githubusercontent.com/72478292/150116441-1abcd675-7c15-40b3-abbb-244424d36c7c.png)

![Screenshot_20220119-115332_Usługi microG](https://user-images.githubusercontent.com/72478292/150116469-10f5e24c-3c57-498a-9c5c-f9d4b45a2c04.png)

**Comment by FriendlyNeighborhoodShane** [comment]
> ```
~ $ su
:/data/data/com.termux/files/home # npem
package com.google.android.gms found
already has permission android.permission.FAKE_PACKAGE_SIGNATURE
package com.android.vending found
already has permission android.permission.FAKE_PACKAGE_SIGNATURE
package com.google.android.gms found
already has permission android.permission.ACCESS_COARSE_LOCATION
package org.microg.nlp.backend.ichnaea found
already has permission android.permission.ACCESS_COARSE_LOCATION
package org.fitchfamily.android.dejavu found
already has permission android.permission.ACCESS_COARSE_LOCATION
package org.microg.nlp.backend.apple found
already has permission android.permission.ACCESS_COARSE_LOCATION
package com.google.android.gms found
already has permission android.permission.ACCESS_FINE_LOCATION
package org.microg.nlp.backend.ichnaea found
already has permission android.permission.ACCESS_FINE_LOCATION
package org.fitchfamily.android.dejavu found
already has permission android.permission.ACCESS_FINE_LOCATION
package org.microg.nlp.backend.apple found 
already has permission android.permission.ACCESS_FINE_LOCATION
package com.google.android.gms found
already has permission android.permission.ACCESS_BACKGROUND_LOCATION
package com.google.android.gms found
already has permission android.permission.RECEIVE_SMS
```

... You actually don't seem to have the sync adapters installed at all. Sure you're using a package which has them?

**Comment by kielichwina** [comment]
Oh, I have android 12 not 11! My mistake!
I flashed minmicroG in TWRP as system:
system-MinMicroG-Standard-UPDATELY-20211205132841.zip

**Comment by kielichwina** [comment]
:P
Thanks for help

**Comment by kondors1995** [comment]
> :P
> 
> The reason for you not having your contacts and calendar synced is because MinMicroG doesn't _have_ the sync adapters for android 12.
> 
> MinMicroG gets the latest sync adapters from [opengapps](https://gitlab.opengapps.org/opengapps/all) and even they don't have them yet. When they add them there, I'll be adding them here.
> 
> Until then you can use DAVx5 or something instead to sync those things.

Way not use ones from nikgapps ?

**Comment by FriendlyNeighborhoodShane** [comment]
> Way not use ones from nikgapps ?

Well, I don't know who they are or what their reputation is. And it doesn't seem like they host a version-controlled source like https://gitlab.opengapps.org to conveniently get the newest version of their assets from either.

**Comment by kondors1995** [comment]
with files are needed for sync adapter i might try to update them my self

**Comment by kondors1995** [comment]
Other option would be to use contacts adapter from gapps shipped with rom like Arrow gapps 

source
https://gitlab.com/yaosp/vendor_google_gms/-/tree/twelve/proprietary/product/app/GoogleContactsSyncAdapter

**Comment by FriendlyNeighborhoodShane** [comment]
> with files are needed for sync adapter i might try to update them my self

ContactSyncAdapter, CalendarSyncAdapter and BackupTransport are the 3 packages you need.
