### ISSUE TITLE
Swype libs for AOSP keyboard

### ISSUE THREAD

**Issue by kielichwina** [FriendlyNeighborhoodShane/MinMicroG#25]
Swype libs for AOSP keyboardare not working in Android 11 (Arrow OS)

**Comment by FriendlyNeighborhoodShane** [comment]
The swipe adapters are known to be very finicky. They're grabbed directly from opengapps, so I'm afraid there's not much I know that you can do to try and make them work if they don't.

I've listed a couple alternatives over in the installation manual: 
https://github.com/FriendlyNeighborhoodShane/MinMicroG/blob/master/INSTALL.md#making-swipe-work-on-aosp-keyboard

**Comment by kielichwina** [comment]
Thanks for info
