### ISSUE TITLE
how can l change my area in Google play?

### ISSUE THREAD

**Issue by jerry460** [FriendlyNeighborhoodShane/MinMicroG#26]
l need change the area ,but l can't

**Comment by FriendlyNeighborhoodShane** [comment]
Uh, I'm not sure? It should work if and however it can be done with vanilla playstore, the patched changes nothing regarding this.

You can also try doing this with aurora store's spoofing mechanism, if they still have it.

**Comment by jerry460** [comment]
thank you for your reply.However, my play store's button of changing areas is unable to touch.(╯︵╰,)
