### ISSUE TITLE
MicroG frequently crash

### ISSUE THREAD

**Issue by jerry460** [FriendlyNeighborhoodShane/MinMicroG#27]
https://paste.crdroid.net/od7WXx
this is the crash report
please help me

**Comment by FriendlyNeighborhoodShane** [comment]
Is this a clean flash? Does force stopping or wiping data for microG GMS core solve the crashes?

What NLP backends are you using?

**Comment by jerry460** [comment]
flash is clean.what is nlp?Does you mean ai?

**Comment by jerry460** [comment]
flash is clean.what is nlp?Does you mean ai?wiping data is useless

**Comment by jerry460** [comment]
> Unified NLP (Network Location Provider) backends are the apps that you go and enable in microG Settings' "Location Modules" screen.
> 
> I assume you must have enabled at least one, since the crash seems to be in NLP-related code.

thank you for your suggestions, the problem has been solved.
