### ISSUE TITLE
[Request] Add Bromite System Webview to NoGoolag Edition

### ISSUE THREAD

**Issue by VesperLlama** [FriendlyNeighborhoodShane/MinMicroG#33]
It would be nice to have [Bromite System Webview](https://www.bromite.org/system_web_view) replace the preinstalled webview. The install instruction for the webview is very unintuituve so it will be helpful if there's a script for it.

The preinstalled one on the ROM that I am using is different than the one on the Play Store, so only the ROM maintainer can update it and thus it is few versions behind than Chromium. Bromite Webview will make it easy to update it on deGoogled phones and will also include the privacy features of Bromite.

**Comment by FriendlyNeighborhoodShane** [comment]
I haven't replied to this issue because while I wasn't sure. I was willing to try, but looking around it seemed getting bromite webview to work these days seems to be a complicated process.

**Comment by FriendlyNeighborhoodShane** [comment]
*accidentally pressed close :facepalm:*

**Comment by FriendlyNeighborhoodShane** [comment]
In the meanwhile, a friend has been working on updating the nanodroid bromite package to work with the newer bromite if you want to try:
https://gitlab.com/zer0def/NanoDroid/-/packages

They're mostly doing it for personal use, so they might not work on issues that don't affect them personally. E.g. apparantly safetynet doesn't work with it for complicated reasons.

**Comment by eredrolo** [comment]
> https://gitlab.com/zer0def/NanoDroid/-/packages

Thanks, but it is not installing on my device. Says that it cannot mount /system_root. ☹️

**Comment by zer0def** [comment]
@eredrolo Sorry about that, I made a hard-to-spot mistake when ripping out Google-related components in NanoDroid and those builds are based on my personal preference branch, not Bromite-related feature one, invariably surfacing the issue. Should be fine with today's build.

**Comment by zer0def** [comment]
@eredrolo That's [what it's supposed to be doing](https://github.com/zer0def/NanoDroid/blob/personal/CommonInstaller#L1119) and has worked for me so far. If it doesn't work, look for `BromiteOverlay.apk` across `overlay` dirs in `/system`, like `find /system -iname bromiteoverlay.apk`.

**Comment by eredrolo** [comment]
@zer0def I don't see any bromiteoverlay.apk file and the webview xml file hasn't changed. Nanodroid logs show that it's installing BromiteOverlay.apk and doesn't give any error.

**Comment by zer0def** [comment]
That means the installation is quietly failing for unknown reasons - is Bromite WebView installed at all and is it installed as a system app?

**Comment by eredrolo** [comment]
@zer0def Yes, Bromite Webview is installed as a system app. I can see it in the apps list and in /system/app/

**Comment by zer0def** [comment]
Without the overlay containing the override adding it the allowed list, it obviously isn't going to work. Would you be able to provide NanoDroid logs from the installation (either as into system, or as a Magisk module)?

**Comment by zer0def** [comment]
Just double-checked with a fresh flash and it might be that the recovery in use is misbehaving in strange ways (likely just expects mounting by `twrp mount <partname>`, instead of relying on fstab). Can't do anything about it without narrowing down the script's scope to be running only on TWRP, which makes no sense of doing.

Glad you managed to get it to work, tho.

**Comment by FriendlyNeighborhoodShane** [comment]
Whoops, bromite is unmaintained now.
