### ISSUE TITLE
Support of Android 12?

### ISSUE THREAD

**Issue by StoppingBuck** [FriendlyNeighborhoodShane/MinMicroG#36]
Hi, I'm running [iodéOS 3 on Fairphone 4](https://github.com/iodeOS/ota/releases/tag/v3-FP4). iodéOS 3 is based in Android 12 (through LOS), so TWRP doesn't work yet and thus flashing MinMicroG through recovery seems to be out of the question.

So I installed Magisk and rooted the phone, but installing MinMicroG as a Magisk module seems to just send the phone into a bootloop.

Looking at NanoDroid I can see that Android 12 is not supported over there yet. Is it the same case with MinMicroG? I couldn't find a list of supported versions.

**Comment by FriendlyNeighborhoodShane** [comment]
Common bootloops with a12 have been fixed, I just haven't had the time to make a stable release since. 

You can find automated builds of the zips here: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases
