### ISSUE TITLE
Can't get IAP Playstore to work [MinMicroG / Magisk / iodéOS 3.0 / FP4]

### ISSUE THREAD

**Issue by StoppingBuck** [FriendlyNeighborhoodShane/MinMicroG#37]
Hey, I've been trying for days on end to get the IAP-patched Playstore working on my Fairphone 4 running iodéOS 3.0.
Finally, I managed to install a version of MinMicroG Standard (as Magisk module) that didn't bootloop my phone - namely [this one](https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.07.05), but when opening the Playstore I either get blank screen, an infinitely spinning wheel or just a frozen picture of the Playstore icon.

I have done everything mentioned [on the wiki](https://www.reddit.com/r/microG/wiki/patchedplay) multiple times over, rebooted, etc., but the problem persists.

I have no idea what I'm missing or what the usual procedure is for seeking help in cases like this. I've attached a logcat from me trying out all of the steps mentioned above, to no avail (I've pseudonomized my name and email, but otherwise it should contain everything). Let me know if I need to provide anything else.

[logcat_07-25-2022_19-29-27.txt](https://github.com/FriendlyNeighborhoodShane/MinMicroG/files/9183606/logcat_07-25-2022_19-29-27.txt)

**Comment by FriendlyNeighborhoodShane** [comment]
> Finally, I managed to install a version of MinMicroG Standard (as Magisk module) that didn't bootloop my phone - namely [this one](https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.07.05)

Ah yes, the last stable release didn't yet support A12. I've been meaning to make a stable release for a while but haven't been able to hit a few milestones.

Just for a formality, the microG self-check screen shows everything all OK, expecially the signature spoofing sections?

**Comment by StoppingBuck** [comment]
> > Finally, I managed to install a version of MinMicroG Standard (as Magisk module) that didn't bootloop my phone - namely [this one](https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.07.05)
> 
> Ah yes, the last stable release didn't yet support A12. I've been meaning to make a stable release for a while but haven't been able to hit a few milestones.
> 
> Just for a formality, the microG self-check screen shows everything all OK, expecially the signature spoofing sections?

Yep, all Checkmarks are checked

**Comment by FriendlyNeighborhoodShane** [comment]
Ah, I just noticed that it was the CI release I made with a modified playstore :P It was pretty buggy.

Use zips from this one: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.05.13
