### ISSUE TITLE
Release package with updated Aurora Store

### ISSUE THREAD

**Issue by Tarek-Hasan** [FriendlyNeighborhoodShane/MinMicroG#38]
Included Aurora Store is an old version resulted in error saying "Failed to connect to goolag.store". Which is pointed out in https://gitlab.com/AuroraOSS/AuroraStore/-/issues/607 that Aurora Store version older than 4.1.1 is unable to connect to service.
And I was also unable to manually update it.
So please release packages with updated Aurora Store.

**Comment by FriendlyNeighborhoodShane** [comment]
See https://github.com/FriendlyNeighborhoodShane/MinMicroG/issues/28
