### ISSUE TITLE
Fix FCM registration for apps using firebase >= 20.1.1

### ISSUE THREAD

**Issue by alexeys85** [FriendlyNeighborhoodShane/MinMicroG#4]
Could you please include [this PR](https://github.com/microg/android_packages_apps_GmsCore/pull/1069) to your builds?

**Comment by FriendlyNeighborhoodShane** [comment]
Hello!

Thanks for informing us and sure!

But just for the record, this repo is just the flashable zip scipts; our microG sources are over at our org @nogoolag
