### ISSUE TITLE
Bootloop after flashing MinMicroG 

### ISSUE THREAD

**Issue by noadhesiveness** [FriendlyNeighborhoodShane/MinMicroG#40]
I flashed the standard version once and then got to following message in TWRP:

ERROR: 1

Error installing zip file

I then booted normally, tried to run a specific app which didn't work and said it needed google play services.
I flashed the same MicroG version again and am stuck in a bootloop since which will always end in recovery mode. How do I fix this?

**Comment by FriendlyNeighborhoodShane** [comment]
> I flashed the standard version once and then got to following message in TWRP:
> 
> ERROR: 1
> 
> Error installing zip file
> 
> I then booted normally, tried to run a specific app which didn't work and said it needed google play services

That really doesn't give me any useful information to help you with here. The actual error message is right above that line, and you know that you can get the full recovery logs, right?

> I flashed the same MicroG version again and am stuck in a bootloop since which will always end in recovery mode. How do I fix this?

Are you on A12? The latest stable release didn't support it. Try this automated nightly build:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.05.13

**Comment by noadhesiveness** [comment]
No, I don't know about the logs. I know very little about this whole topic. So I'm running the most recent version of LineageOS for the Pixel 3a which is based on Android 12. Do you recommend to flash the auto version linked over it once again?
Also, here's the picture of the full error, in case that helps you: [https://postimg.cc/MvHr09BC](url)
Thanks!

**Comment by FriendlyNeighborhoodShane** [comment]
> No, I don't know about the logs. I know very little about this whole topic.

I see, that's absolutely fine. Recoveries have an internal log that it and the zips you flash can log debug information to when they need to, and most recoveries allow users to save those logs to a file, so they can send it to the recovery/flashable zip creator. In TWRP, you can do this in `Advanced` > `Copy logs` (you need to have a decrypted data partition).

> Also, here's the picture of the full error, in case that helps you: https://postimg.cc/MvHr09BC

Interesting. That's a very weird error. I can't really say anything without having the logs, but it looks like your system partition might be unwriteable. In twrp, make sure in the `Mount` screen, system or system_root is mounted, but `Mount system partition as read-only` is unchecked.

> So I'm running the most recent version of LineageOS for the Pixel 3a which is based on Android 12. Do you recommend to flash the auto version linked over it once again?

Yep, you should try flashing that one instead for A12. If it still doesn't work, you should get those recovery logs.

**Comment by noadhesiveness** [comment]
Thanks for your help! The system is now running again.

**Comment by FriendlyNeighborhoodShane** [comment]
Cool!
