### ISSUE TITLE
[Request] Something between standard and minimalIAP?

### ISSUE THREAD

**Issue by the4anoni** [FriendlyNeighborhoodShane/MinMicroG#45]
Hi
Like in topic.
It would be nice if we could get something between two variants.

MicroG (GMSCore, GSFProxy, Maps APIv1) (from MicroG FDroid repo)
Google Play store (modded for IAPs by Setialpha)
UNLP backends (Dejá vu, LocalGSM, LocalWiFi, Mozilla, Nominatim) (From FDroid repo)
Swype libs for AOSP keyboard (From OpenGApps GitHub repo)
Some Google DRM jars (From OpenGApps GitHub repo)
Google Sync adapters for KK to T (From OpenGApps GitHub repo)
Permission files for all of this
An addon.d file to backup/restore everything on a rom flash

**Comment by FriendlyNeighborhoodShane** [comment]
Sorry for the late response. I was busy IRL and wasn't able to work on MinMicroG in the last couple months.

For obvious reasons, it's not feasible for me to add configurations for every user's taste; everybody has different preferences on what they would want in a package tailored to themselves. And this problem wouldn't be so bad if modern recoveries hadn't killed graphical installers like AROMA where you could interactively change configuration without dealing with confusing and fallible text files.

https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.12.31

I added a new addon package for UNLP backends. Flashing MinimalIAP + UNLPBackends should cover most of what you want; for contact sync, you can use DAVx5 as shown here: https://github.com/FriendlyNeighborhoodShane/MinMicroG/blob/master/INSTALL.md#contact-sync
