### ISSUE TITLE
Contacts sync adapter does not work on Android 12L

### ISSUE THREAD

**Issue by MinusAlternative** [FriendlyNeighborhoodShane/MinMicroG#46]
Tried in many ROMs. Also tried the latest abuse-ci build. Maybe this is a known issue as working sync adapters from KitKat to R are mentioned on the info page. But fix this ASAP please. Thank for your awesome work.

**Comment by FriendlyNeighborhoodShane** [comment]
Contact sync adapters for S to T have been added, taken from MindTheGApps:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.12.31

Stable builds will come soon :tm:
