### ISSUE TITLE
time for a new release

### ISSUE THREAD

**Issue by HritwikSinghal** [FriendlyNeighborhoodShane/MinMicroG#47]
many fixes for A13 are there in commits but the release was a long time ago. Since microG gmscore was recently updated, maybe its time for a new release.

**Comment by FriendlyNeighborhoodShane** [comment]
I do plan to make a new release after I get some time and address the other issues, but in the meanwhile, I made a CI build with the A13 commits: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.10.30

**Comment by FriendlyNeighborhoodShane** [comment]
Sorry for taking a while, I made a release:
https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/tag/2023.07.29

**Comment by HritwikSinghal** [comment]
> Sorry for taking a while, I made a release: https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/tag/2023.07.29

no worries :)
