### ISSUE TITLE
2.7-beta3 will not install

### ISSUE THREAD

**Issue by MrDrMcCoy** [FriendlyNeighborhoodShane/MinMicroG#5]
In TWRP, if I attempt to flash 2.7-beta3, it errors out with `!!! FATAL ERROR: Could not find a ROM in /`

Running Havok 3.5 on ASUS RoG Phone 2 with its built-in TWRP. Same error occurs with Lineage and the latest TWRP.

Thanks for this project, I can't wait to get it working!

**Comment by FriendlyNeighborhoodShane** [comment]
Try mounting system by hand from TWRP's mount menu, and then flashing. If that was the problem, it was fixed a while after the last release with 9e5c0cfc2ab5c775ec0db6c162b767937b28f810

Planning to make a new one with the microG changes sometime soon.

**Comment by MrDrMcCoy** [comment]
That worked, thanks!
