### ISSUE TITLE
Microg No goolag version doesn't not install with twrp and Crdroid 9.3

### ISSUE THREAD

**Issue by Pitoucol** [FriendlyNeighborhoodShane/MinMicroG#51]
Hello

It was easy to get nogoolag package installed with Crdroid 7 and 8. Into twrp, I used to flash both zip files and everything was fine. 
But with the install of Crdroid 9, there's some problems. I have no error message during installation, but after reboot, microg isn't installed at all. 

So, I achieved to install all microg apk, one after each other, from fdroid and everything works fine. But it's so much easier to do the install with your package....
Thanks for your work !

**Comment by Mollomm1** [comment]
same with los 19

**Comment by FriendlyNeighborhoodShane** [comment]
Hi,

Sorry for the late reply. Are you still facing this issue?
Please tru this more-up-to-date build:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2023.07.29

**Comment by Pitoucol** [comment]
Hi

just tested, no error message after installation, but no microg icon after (minimal package, so no aurora store or droid). Seems that nothing appened

**Comment by FriendlyNeighborhoodShane** [comment]
Can you try flashing it again and this time, grab a recovery log after the flash?

**Comment by Pitoucol** [comment]
Oh sorry, I should have done this.

[recovery.log](https://github.com/FriendlyNeighborhoodShane/MinMicroG/files/12213139/recovery.log)

**Comment by FriendlyNeighborhoodShane** [comment]
So it seems the installation went okay. It was a system install, so if you have magisk installed, are you sure there's no magisk module interfering with it e.g. another microG or gapps package?

Also, you have an A/B device, so are you certain that nothing is switching slots? Here MinMicroG got installed to slot b. Remember:
 - A ROM flash gets flashed to the inactive slot, and then schedules a slot switch when you reboot
 - Everything else gets flashed to the currently-active slot
So if you install your ROM and other zips in one go, you have to flash ROM, reboot to recovery, flash other zips, then boot.

Using a file manager (e.g. Mixplorer) that can navigate to /system on booted Android, can you see the file `/system/priv-app/MicroGGMSCore/MicroGGMSCore.apk`?

**Comment by FriendlyNeighborhoodShane** [comment]
Great! was it the slot being wrong?

**Comment by Pitoucol** [comment]
yes, I've misunderstood how to deal with the two slots.... I made the old way, flashing both ROM+minmicrog together, and rebooting after.
