### ISSUE TITLE
PlayStore still remains

### ISSUE THREAD

**Issue by ghost** [FriendlyNeighborhoodShane/MinMicroG#56]
i installed MinAddon-Playstore-Playstore-2.12.0-20230729205900.zip as magisk module

then deleted it, but the playstore app is still installed.
even after i removed magisk.

**Comment by FriendlyNeighborhoodShane** [comment]
That's just a regular user app, you can simply uninstall it. Playstore and GMS have to be installed as a user app update over the system overlays because android is fussy about certain permissions otherwise.

**Comment by FriendlyNeighborhoodShane** [comment]
> > That's just a regular user app, you can simply uninstall it.
> Yes, it's just a regular user app. And it should be easier to just hit the "uninstall" button But there is no "uninstall" option, only "disable".

That's

**Comment by FriendlyNeighborhoodShane** [comment]
My bad, the mobile UI isn't suited for my butter fingers.

> > That's just a regular user app, you can simply uninstall it.
> Yes, it's just a regular user app. And it should be easier to just hit the "uninstall" button But there is no "uninstall" option, only "disable".

That's weird. That means it's still a system app. Are you sure it wasn't a system installation? That would explain why it didn't go away with magisk. Or you might have a system install that was lying below the magisk install all along.

If the minmicrog/addon packages are flashed in recovery without a decrypted data, they have no way to detect the existence of an older version of itself, or even magisk, so by default it installs to system.

**Comment by ConcurrentCrab** [comment]
> > That means it's still a system app.
> 
> It seems like.
> 
> > Are you sure it wasn't a system installation?
> 
> Fresh install LineageOS for microG + Magisk... twice The addon is installed using Magisk Manager.
> 
> I don't even use recovery at all. The reason I installed it using Magisk is because I can't install it using recovery. Due to an error not enough storage on the system or something like that. I forgot the error message.
> 
> > That would explain why it didn't go away with magisk.
> 
> As what I said before. If the module is removed from magisk manager before playstore gets an automatic update. The problem does not occur.

Hi, sorry for the late reply.

I see, then. I'm not sure what could be causing such behaviour. Does playstore "promote" itself to a pseudo-system app on updates? Or is this just a bug in android?

**Comment by FriendlyNeighborhoodShane** [comment]
Hi,
Sorry for the late reply. Not sure what's causing this behaviour then. Is playstore promoting itself to a pseudo-system app? Or is this a bug in android?

**Comment by FriendlyNeighborhoodShane** [comment]
I guess I'll reopen this issue, though I'm still not sure how this is caused. I'll try to reproduce it, and see if adding the `pm uninstall` command would fix it. Though it could only be run on Magisk uninstalls, not on system.

**Comment by FriendlyNeighborhoodShane** [comment]
About the free space thing, the answer lies in the log you posted:
```
[  636.226897] Pack size is 156
[  636.248079] Free space in /mnt/system is 2
```
These sizes are in MBs. You have a dynamic partition layout where there's no space reserved in `/system` for user mods. Your ROM maintainer can fix this: https://github.com/FriendlyNeighborhoodShane/MinMicroG/issues/19#issuecomment-918548245
