### ISSUE TITLE
[Request] Add Mulch System Webview to NoGoolag edition

### ISSUE THREAD

**Issue by MIOGMIOG** [FriendlyNeighborhoodShane/MinMicroG#57]
It would be great to add [Mulch System Webview](https://divestos.org/pages/our_apps#mulch) as Android System Webview replacement. 
(This is literally #33, but with different webview, I made this issue because Bromite is no longer maintained)
Mulch System Webview doesnt need to be maintained that much, because it uses script to download latest chromium and vanadium patches and merge it every day
(they say `Included patches must be very simple to minimize maintenance`, so messing with it isn't needed that much)

**Comment by Tarek-Hasan** [comment]
Mulch has not been updated for over a year now. Instated, you should check out [Cromite](https://github.com/uazo/cromite), an actively maintained Bromite fork.

**Comment by FriendlyNeighborhoodShane** [comment]
Unfortunately, Cromite doesn't seem to have system webview builds. And the maintainer doesn't have intentions to compile it: https://github.com/uazo/cromite/issues/159#issuecomment-1671912779

So out of the few candidates for a system webview build (cromite and vanadium) neither seem to provide builds for 3rd party installs.

**Comment by MIOGMIOG** [comment]
> Mulch has not been updated for over a year now. Instated, you should check out [Cromite](https://github.com/uazo/cromite), an actively maintained Bromite fork.

But Mulch is getting updates on their f-droid repo for some reason
![image](https://cdn.discordapp.com/attachments/1041315363184463946/1146769257334583346/j9YTgKwb.jpg)

**Comment by MIOGMIOG** [comment]
Yeah, its bad that its no longer maintained, but it still gets updated from upstream every day - Latest build of mulch on F-Droid is based on latest chromium and has all latest vanadium patches (checked the source code too)
I still consider this an usable option, even that latest non-automated commit on Mulch github/gitlab is 1 year old (maybe because Im a weird person lol)

**Comment by MIOGMIOG** [comment]
hey, mulch gitlab gets updated every day (they automate it, it doesnt need much maintainance) with latest chromium and vanadium patches, also they say `Included patches must be very simple to minimize maintenance` in their gitlab repo

**Comment by mahe8186** [comment]
I was wondering why you need webview in the first place!

If you have Vanilla Rom, you'll probably have chromium webview by defalut.

And you can always choose to replace in the developer settings.

**Comment by MIOGMIOG** [comment]
Divestos got discontinued :(
https://divestos.org/pages/news#end
