### ISSUE TITLE
Play Store microG check - always missing

### ISSUE THREAD

**Issue by bugsyb** [FriendlyNeighborhoodShane/MinMicroG#58]
Android 13. 
After installing any of variants, including Standard one, checking microG Self-Check:
- Play Store (Phonesky) installed: (is not marked).

De-googling phone, prepping for MinMicroG install, there were troubles to remove `com.google.android.gms` and only after `adb uninstall --user 0 com.google.android.gms` succeeded.

Aurora shows up as installed, could install packages and most of apps work. Most, as one I've stumbled on is "Tile" which complains about missing "Play Store".

Not sure what to do to further troubleshoot where the problem is. Is it in microG/MinMicroG or maybe FakeStore?

All other checks are on. LSposed on, FakeStore module in it too.

**Comment by bugsyb** [comment]
Did additional test - Factory reset, clean Magisk (Zygisk) install + module. Needed to add LSPosed for Signatures.
Same situation as above.
No error on install.

**Comment by bugsyb** [comment]
Further tests.... after one of factory resets, somehow I got it working. As had it fresh, thought will repeat steps, another factory reset and same steps (simply installing Magisk apk and modules LSPosed Zygisk, FakeGapps, and MinMicroG didn't work - this time not even showing up microG icon in launcher. Since then did full Odin reflash and still can't get microG showing up, tried to install it from adb shell and getting (tried with latest version from microG GitHub:
```
 adb install com.google.android.gms-231657056.apk 
Performing Streamed Install
adb: failed to install com.google.android.gms-231657056.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 231657056 is older than current 233316045]
```

Which makes me feeling that Google  is still present on the phone even if:
```
pm list packages|grep -i gmscore
```
returns nothing though:
```
adb uninstall --user 0 com.google.android.gms
Failure [not installed for 0]
```

Solved - how? I don't know as nothing different was done:
- yet another factory reset,
- same packages in same order installed (Factory Reset, setup of everything, reboot, Magisk, reboot, module install, reboot).
The only difference I can think of is timing - after setting up everything I've left it for a bit longer (maybe something was being set up in the background and I didn't let it finish - this was probably related to some Play Store settings after factory reset, before installing Magisk.

**Comment by bugsyb** [comment]
Ok, yet another factory reset and data blocked as quickly as possible. 
This helped stopping Play Store/Framework updates in the background and managed to get at leat microG (gmscore) installed.

**Comment by FriendlyNeighborhoodShane** [comment]
Hi, sorry for the late reply.

The `pm uninstall --user` way of doing things is always going to be spotty, because it doesn't actually remove the relevant apps from your device, only sort of "super disables" them. That said, if you're still having troubles with the sms/location permissions, just run `npem` from an adb or root shell. Or install the microG apk as a simple app update.

**Comment by Kenajcrap** [comment]
I'm experiencing the same intermittent problem, same setup, same apps involved, same signature spoofing method, same situation where sometimes after a full reset back to factory rom through odin and a full setup, Phonesky check in microG's self-check is not ticked.

**Comment by FriendlyNeighborhoodShane** [comment]
Hi @Kenajcrap,

did you debloat your stock rom using the `pm uninstall --user` method like the above poster, or did you use some other tool that removes the actual apk from your system?
