### ISSUE TITLE
Not enough free space in your /mnt/system

### ISSUE THREAD

**Issue by m93a** [FriendlyNeighborhoodShane/MinMicroG#60]
I did a fresh LineageOS install on OnePlus Nord, then I tried sideloading MinMicroG via the LineageOS Recovery, and the script failed with:
```
Doing size checks...

!!! FATAL ERROR: Not enough free space in your /mnt/system

Stopping installation and Uninstalling...

Installation failed!
ERROR:    recovery: Error in /sideload/package.zip (status 1)

Installation completed with status 1.
Installation aborted.
```

**Comment by m93a** [comment]
This is the output of `adb shell df`:
```
adb shell df                                             
Filesystem     1K-blocks  Used Available Use% Mounted on
rootfs           3626120 30784   3595336   1% /
tmpfs            3782352  1688   3780664   1% /dev
tmpfs            3782352     0   3782352   0% /mnt
tmpfs            3782352     0   3782352   0% /apex
tmpfs            3782352     4   3782348   1% /linkerconfig
tmpfs            3782352    68   3782284   1% /tmp
tmpfs            3782352     0   3782352   0% /storage
```

**Comment by FriendlyNeighborhoodShane** [comment]
Hi, sorry for the late reply.

It's pretty much as it says. I suspect `/dev/block/dm-17` is your system partition, and you have either 56mb or 28mb space free in it (`df`'s behaviour without the `-P` or `-h` flags is not standardised, IDK how the android one behaves), either of which is too low for microG and friends these days. If you save the recovery log after flashing it, the installer script logs (in more clearer units) how much space it wants and how much it finds.

But really, what this essentially means is that you're using a dynamic partition device, where your partitions are sized almost exactly to fit whatever the ROM includes and nothing more. You'll need to ask your ROM maintainer to expand that free space, if only for the vanilla/nogapps variant:
https://github.com/FriendlyNeighborhoodShane/MinMicroG/issues/19#issuecomment-918548245
