### ISSUE TITLE
How do I add minmicroG to some store like Fdroid or Aurora droid for automatic updates?

### ISSUE THREAD

**Issue by Mkcein** [FriendlyNeighborhoodShane/MinMicroG#61]
How can I add MinMicroG (I use NoGoolag) to any of these stores via the repository, for every time updates come out of either the MICROG modules or even the stores it does automatically? I didn't find a repository to add to the F-droid of this MinMicroG package so that it identifies and updates itself. There is a way to do this?
I am a layman if you can explain in more detail how to put in order for updates to MinMicroG add-ons to be done automatically by any store, it can be F-droid or Aurora Droid, etc.

It has the address of the MinMicroG repository ?

**Comment by FriendlyNeighborhoodShane** [comment]
Hi @Mkcein,

minmicroG is just the installer script (in addition to the update addon.d script). It doesn't really need to be updated, unless there is a bugfix for those things, which is very rare.

Most of what it contains, that is the apps in it, can however be updated through their respective upstream sources:
- microG from the official microG F-Droid repo https://microg.org/fdroid/repo
- Aurora apps from the AuroraOSS gitlab releases https://gitlab.com/AuroraOSS (but they self-update)
- pretty much all of the other apps from the main F-Droid repo

The patched play store comes from the nanolx F-Droid repo too, but that hasn't been updated for quite a while and it probably won't be anytime soon. It's kind of up in the air what should be done about that.

**Comment by Rafee-M** [comment]
It says incompatible version

![Screenshot_2023-12-09-00-10-43-95_f197bb7f6f96b8975c81936709066603](https://github.com/FriendlyNeighborhoodShane/MinMicroG/assets/69535896/68aa7117-c1bd-4c83-9642-e93c8d08c21c)

**Comment by FriendlyNeighborhoodShane** [comment]
What F-Droid client is that? try downloading the APK and manually installing the update from their [GitHub](https://github.com/microg/GmsCore/releases/): https://github.com/microg/GmsCore/releases/download/v0.3.0.233515/com.google.android.gms-233515000.apk

**Comment by Rafee-M** [comment]
Yeah that worked. And manually downloading the apk from f-droid (through the client) worked as well. Seems to be a issue with Neo Store

**Comment by FriendlyNeighborhoodShane** [comment]
Yes, microG fakes its app signature for its functionality, which means signature comparison in the naive way fails.

I'd open an issue in the Neo Store repo and ask them to reference what the official F-Droid client code is doing for this.

**Comment by Etsinshao** [comment]
> 是的，microG 伪造了其应用程序签名来实现其功能，这意味着以简单的方式进行的签名比较会失败。
> 
> 我会在 Neo Store repo 中打开一个问题并请他们参考官方 F-Droid 客户端代码对此所做的事情。

does this mean updates from Fdroid will fail ?
