### ISSUE TITLE
can't build releases

### ISSUE THREAD

**Issue by DieuDeGlace** [FriendlyNeighborhoodShane/MinMicroG#62]
Trying to build, and i can use ./build.sh all just fine, but it seems doing update.sh first doesnt do anything, doesnt execute anything nor do anything from the looks of it so i cannot have the necessary apks ready. If anyone is able to help I would greatly appreciate it!

**Comment by FriendlyNeighborhoodShane** [comment]
That is... really weird? Are you sure you haven't unintentionally made anychanges to `update.sh`? Also that you're using the right shell to run the script? (any POSIX-compatible shell will do, like bash, zsh, etc. but not e.g. fish, or powershell if you're on windows.)

**Comment by DieuDeGlace** [comment]
None that I know of, and I use git bash (I'm on windows) didn't know power shell works too

**Comment by DieuDeGlace** [comment]
It "runs" update.sh, but doesn't do anything at all as in it doesn't make any files. The build.sh all does everything but claims apks are missing (go figure as update.sh isn't grabbing them)

**Comment by DieuDeGlace** [comment]
Idk how I could edit the .sh file but if I could I'll see if something got bugged

**Comment by DieuDeGlace** [comment]
okay idk what happened, but deleted the old folder, cloned a new one and now it just works? dont know what happened but i guess something messed up

**Comment by FriendlyNeighborhoodShane** [comment]
:)
