### ISSUE TITLE
Deprecate or rename MinimalIAP variant

### ISSUE THREAD

**Issue by hmtheboy154** [FriendlyNeighborhoodShane/MinMicroG#65]
The latest version of microG (Services Core & Companion) now support License Verification and In-App Purchases so microG Companion is not a placeholder like FakeStore anymore. I think MinimalIAP should be deprecated or rename to something like MinimalPhonesky in case some user still want  Play Store to buy apps.

**Comment by FriendlyNeighborhoodShane** [comment]
Good point, thanks.

BTW, have you tried making in app purchases with this new update? Asking because I haven't had a chance to test that myself yet.

**Comment by hmtheboy154** [comment]
![photo_2024-03-24_14-41-26](https://github.com/FriendlyNeighborhoodShane/MinMicroG/assets/39849246/dc89b1ca-6782-4c14-910d-dffd91cd6f81)
![photo_2024-03-24_14-41-21](https://github.com/FriendlyNeighborhoodShane/MinMicroG/assets/39849246/7c95666d-76b7-4248-9345-c1bfc9df2d7a)

Tested a small purchase on Touhou LostWord, it work just like Play Store one. Here I am using my phone bill to pay.

I haven't tried License Verification yet, as the only app I got are PowerAMP & PowerAMP EQ and both of them are already activated.

**Comment by FriendlyNeighborhoodShane** [comment]
Done with https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/5426bebd0bdc2414325e7d969456648722bb19d4
