### ISSUE TITLE
Google Play Store and FakeStore is not installed for current user

### ISSUE THREAD

**Issue by Nonononoki** [FriendlyNeighborhoodShane/MinMicroG#7]
Version: 27th july 2020
OS: Android 10 (AEX)
Phone: Sony XZ1 Compact

Complete noob here. I tried just installing the zip (both versions) as a Magisk module, but com.android.vending won't be installed for the only user on the phone and only states "App is not installed for current user" in the Settings. Any advice?

**Comment by Nonononoki** [comment]
@FriendlyNeighborhoodShane Yes, the ROM had PlayStore pre-installed and I had to use an app to remove it (https://f-droid.org/repo/org.droidtr.deletegapps). I'll try your suggestions later, thanks a lot!

**Comment by FriendlyNeighborhoodShane** [comment]
@Nonononoki Cool.

It can be automated under certain conditions (only for updates in Magisk mode from the manager, you can't run `pm` in recovery) but you don't really want it to be. It'll wipe data for play store every time it's run.
